import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./Layout.module.css"; // <-- add this
import StoreProvider from "./StoreProvider";
import GlobalWrapper from "./components/GlobalDataLoader";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";
import AppLayoutClient from "./AppLayoutClient";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "./ThemeContext";

export const metadata = {
  title: "HR Exports IMS",
  description: "Generated by Shazia Rice Team",
  applicationName: "HR Exports IMS",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)",  color: "#0b0b0b" },
  ],
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-inter" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"], display: "swap" });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"], display: "swap" });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* use the module class here */}
        <a href="#main" className={styles.skipLink}>Skip to content</a>

        <ThemeProvider>
          <SessionProvider>
            <StoreProvider>
              <GlobalWrapper>
                <Toaster position="top-right" />
                <Suspense fallback={null}>
                  <AppLayoutClient>{children}</AppLayoutClient>
                </Suspense>
              </GlobalWrapper>
            </StoreProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
