import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import styles from './Layout.module.css';
import { Inter } from 'next/font/google';
import StoreProvider from "./StoreProvider";
import GlobalWrapper from './components/GlobalDataLoader';
import { SessionProvider } from "next-auth/react";
import { Suspense } from 'react';
import AppLayoutClient from "./AppLayoutClient";
import { Toaster } from 'react-hot-toast';
import Topbar from "./components/Topbar";
import { ThemeProvider } from "./ThemeContext";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', // optional: improves performance
  variable: '--font-inter', // optional: useful for Tailwind CSS
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HR Exports IMS",
  description: "Generated by Shazia Rice Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>

        <Suspense fallback={null}>

          <ThemeProvider>
            <SessionProvider>
              <StoreProvider>
                <GlobalWrapper>

                  <Toaster position="top-right" />

                  <AppLayoutClient>
                    {children}
                  </AppLayoutClient>

                </GlobalWrapper>
              </StoreProvider>
            </SessionProvider>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}

// For react context api we use DataProvider wrapper.