import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import styles from './Layout.module.css';
import { Inter } from 'next/font/google';
import StoreProvider from "./StoreProvider";
import GlobalWrapper from './components/GlobalDataLoader';
import { SessionProvider } from "next-auth/react";
import { Suspense } from 'react';
import AppLayoutClient from "./AppLayoutClient";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', // optional: improves performance
  variable: '--font-inter', // optional: useful for Tailwind CSS
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HR Exports IMS",
  description: "Generated by Shazia Rice Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}
       `}
        // style={{ display: "flex", maxHeight: "100vh" }}
       >

<Suspense fallback={null}>

        {/* ${styles.bodyCss} ${geistSans.variable} ${geistMono.variable} */}
        <SessionProvider>
          <StoreProvider>
            <GlobalWrapper>

              <AppLayoutClient>
                {/* <main className={styles.mainContent}> */}
                  {children}
                {/* </main> */}
              </AppLayoutClient>

            </GlobalWrapper>
          </StoreProvider>
        </SessionProvider></Suspense>
      </body>
    </html>
  );
}

// For react context api we use DataProvider wrapper.